### PR TITLE
add "rtl" styles for select element

### LINKED ISSUE #86: "rtl" style for the select element
### What version of @tailwindcss/forms are you using?

v0.3.4

### What version of Node.js are you using?

v14.0.0

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/let-lc/tailwindcss-forms/tree/rtl-issue-reproduction

### Describe your issue

I recently work on a project that needs to change the direction to "rtl" when changing the site language to Arabic, and the project has the tailwindcss-forms plugin installed. I noticed all the form elements I used are rendering "rtl" normally except the `<select>` element.

A raw, no styles select element with "rtl" direction displays the chevron down icon on the left side, shows here [https://play.tailwindcss.com/lORpOqPWap](https://play.tailwindcss.com/lORpOqPWap). However, the tailwindcss-form plugin always has the icon displaying on the right side.

In the reproduction branch, I set the "Unstyled" section to "rtl" to show the issue.

I think we should have the select element resemble the "rtl" style of a raw,no styles select element by putting the chevron icon on the left side. I currently overrided some styles of the tailwindcss-form to fix the issue in my project, but I think this should be supported by the plugin natively.

I already worked on a solution and ready to submit a PR, but I know the [contributing guidelines](https://github.com/tailwindlabs/tailwindcss/blob/master/.github/CONTRIBUTING.md) is issue first then PR, so here's description for the issue.

And here is the "ltr" and "rtl" comparison I worked on:
select-rtl

### PR DESCRIPTION
**Pull request by let-lc**
Fixes #86 

The change can be tested by changing `index.html`'s main `<div>` dir property to "rtl".

### CODE REVIEW

**Comment by reinink** [comment]
Hey thanks for this contribution!

So while this seems like a good addition, we haven't actively pursued RTL support in Tailwind CSS yet. That said, we have added new `rtl` and `ltr` variants in the upcoming v3.0 release, so timing wise it might make sense for us to also support this in the forms plugin.

However, if we do, we'll want to make sure other inputs are working properly too. One issue I see is with the checkboxes, but I think that's actually not related to this plugin, and only the demo implementation.

image
image

**Comment by let-lc** [comment]
> One issue I see is with the checkboxes, but I think that's actually not related to this plugin, and only the demo implementation.

Yes, the gap is the margin spacing from the label. The checkbox should be fine.

So far other input elements supported by this plugin work fine on "rtl" direction as I checked. The select element works fine also, and the style is okay, but I think it should resemble the behavior of the native select element which the chevron icon should switch position when switching to "rtl" direction. I am no expert on the "rtl" subject either, but this is one thing I spotted during a development of a "rtl" required site and I think this can be a minor improvement to the plugin.

As always, big thanks to the Tailwind team for this awesome framework, can't way to see the official release of TailwindCSS 3.0.

**Comment by mohamedsabil83** [comment]
Came to make the same PR and found this :smile:. I did the same thing in another project using this package.

Hope to merge it soon as I needed for many projects.

**Comment by danharrin** [comment]
Thanks for this fix @let-lc!

As someone who maintains an open source project with RTL support, this really helps us reduce the custom CSS we're using.

**Comment by adamwathan** [comment]
Hey thanks for the contribution! Unfortunately I am going to close this because the proposed solution has a few issues:

1. The selector `[dir="rtl"] select` has a specificity of `011` which means it can't be overridden with utility classes.
2. The style provided for the class strategy aren't scoped to RTL layouts, so if I merged this the chevron would be on the wrong side even on LTR sites.

Definitely not opposed to adding support for this if the solution is sound, but unfortunately this PR isn't quite where it needs to be in its current state. Right now I personally have higher priority things I need to work on so can't invest any time into this issue myself, but happy to look at another PR that adds support for this without introducing any other issues.

Thanks for the contribution regardless, I appreciate it! ❤️

**Pull request closed without merging**
